# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# hello

trigger:
- stage
- main

variables:
- name: system.debug
  value: true 

pool:
  vmImage: windows-latest

steps:
- task: Restore code
  inputs:
    command: 'restore'
    projects: 'ArchiSteamFarm.sln'
    feedsToUse: 'select'

- task: Publish code
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'ArchiSteamFarm/ArchiSteamFarm.csproj'
    arguments: '-c "Release" -f "net6.0" -o "out/generic"'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Test'
    organization: 'sahanaumesh'
    scannerMode: 'MSBuild'
    configMode: 'manual'
    ProjectKey: 'sahanasu93_Demotest'
    ProjectName: 'Demotest'

- task: Build code
  inputs:
    command: 'build'
    projects: 'ArchiSteamFarm.sln'

- task: Testcode
  inputs:
    command: 'test'
    projects: 'ArchiSteamFarm.Tests/ArchiSteamFarm.Tests.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: Test code coverage
  inputs:
    command: 'test'
    projects: 'ArchiSteamFarm.Tests/ArchiSteamFarm.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --collect "Code coverage"'

- task: Publish
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: Copy artifacts
  inputs:
    Contents: 'out/generic/ArchiSteamFarm.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: Copy sonarcloud files
  inputs:
    Contents: '.scannerwork/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: Copy sonarcloud analysis
  inputs:
    Contents: '.sqAnalysis/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: Publish BuildArtifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'archi'
    publishLocation: 'Container'
